### ISSUE TITLE
Why the kotlin-dsl plugin?

### ISSUE THREAD

**Issue by StefMa** [StylingAndroid/Prefekt#2]
Are there any good reasons why you are adding the kotlin-dsl plugin?

https://github.com/StylingAndroid/Prefekt/blob/941a5dd5eeb591c05d4fe482f6de262843e40071/buildSrc/build.gradle.kts#L2

These plugin adds a lot of stuff which is totally unnecessary for *this* project.
See [KotlinDslPlugin](https://github.com/gradle/kotlin-dsl/blob/master/plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPlugin.kt) and [EmeddedKotlinPlugin](https://github.com/gradle/kotlin-dsl/blob/master/plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/embedded/EmbeddedKotlinPlugin.kt).

Since you only need Kotlin I do recommend to only apply the [kotlin-jvm plugin](https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm) and the kotlin stdlib dependency:
```kotlin
plugins {
  kotlin("jvm") version("1.2.21")
}

repositories {
  jcenter()
}

dependencies {
  implementation(kotlin("stdlib"))
}
```

**Comment by StylingAndroid** [comment]
It's part of the version management scheme that I am using throughout and therefore cannot be removed. It is only used in `buildSrc` so has no impact on the main library output.
